import type { ReactNode } from 'react';
import { 
  Shield, 
  Brain, 
  Search, 
  Globe, 
  Compass, 
  Eye, 
  Terminal, 
  Workflow, 
  MousePointerClick, 
  Cpu, 
  Router, 
  ShieldAlert, 
  Printer, 
  Layers, 
  Upload, 
  Layout 
} from 'lucide-react';

export interface Product {
  cmd: string;
  badge: string;
  status: string;
  title: string;
  desc: string;
  bestFor: string;
  automates: string;
  features: string[];
  href: string;
  button: string;
  icon: ReactNode;
  tone: string;
  demoType: string;
  proHint: string;
  category: 'context' | 'security' | 'system';
}

export const getRouteForCmd = (cmd: string): string => {
  if (cmd === 'symeraseme') return 'eraseme';
  if (cmd === 'symvibe') return 'vibecoder';
  if (cmd === 'symdesk') return 'desktop';
  return cmd.replace(/^sym/, '');
};

export const getProducts = (t: any): Product[] => [
  {
    cmd: 'symvault',
    badge: t('vaultBadge'),
    status: t('vaultStatus'),
    title: t('vaultTitle'),
    desc: t('vaultDesc'),
    bestFor: t('vaultBestFor'),
    automates: t('vaultAutomates'),
    features: [t('vaultFeature1'), t('vaultFeature2'), t('vaultFeature3'), t('vaultFeature4')],
    href: 'https://github.com/danieljustus/symaira-vault',
    button: t('vaultBtn'),
    icon: <Shield size={24} />,
    tone: 'gold',
    demoType: 'vault',
    proHint: t('vaultProHint'),
    category: 'security',
  },
  {
    cmd: 'symmemory',
    badge: t('memoryBadge'),
    status: t('memoryStatus'),
    title: t('memoryTitle'),
    desc: t('memoryDesc'),
    bestFor: t('memoryBestFor'),
    automates: t('memoryAutomates'),
    features: [t('memoryFeature1'), t('memoryFeature2'), t('memoryFeature3'), t('memoryFeature4')],
    href: 'https://github.com/danieljustus/symaira-memory',
    button: t('memoryBtn'),
    icon: <Brain size={24} />,
    tone: 'violet',
    demoType: 'memory',
    proHint: t('memoryProHint'),
    category: 'context',
  },
  {
    cmd: 'symseek',
    badge: t('seekBadge'),
    status: t('seekStatus'),
    title: t('seekTitle'),
    desc: t('seekDesc'),
    bestFor: t('seekBestFor'),
    automates: t('seekBestFor'), // note: using bestFor as per original Tools.tsx line 63
    features: [t('seekFeature1'), t('seekFeature2'), t('seekFeature3'), t('seekFeature4')],
    href: 'https://github.com/danieljustus/symaira-seek',
    button: t('seekBtn'),
    icon: <Search size={24} />,
    tone: 'coral',
    demoType: 'seek',
    proHint: t('seekProHint'),
    category: 'context',
  },
  {
    cmd: 'symfetch',
    badge: t('fetchBadge'),
    status: t('fetchStatus'),
    title: t('fetchTitle'),
    desc: t('fetchDesc'),
    bestFor: t('fetchBestFor'),
    automates: t('fetchAutomates'),
    features: [t('fetchFeature1'), t('fetchFeature2'), t('fetchFeature3'), t('fetchFeature4')],
    href: 'https://github.com/danieljustus/symaira-fetch',
    button: t('fetchBtn'),
    icon: <Globe size={24} />,
    tone: 'sky',
    demoType: 'fetch',
    proHint: t('fetchProHint'),
    category: 'context',
  },
  {
    cmd: 'symscope',
    badge: t('scopeBadge'),
    status: t('scopeStatus'),
    title: t('scopeTitle'),
    desc: t('scopeDesc'),
    bestFor: t('scopeBestFor'),
    automates: t('scopeAutomates'),
    features: [t('scopeFeature1'), t('scopeFeature2'), t('scopeFeature3'), t('scopeFeature4')],
    href: 'https://github.com/danieljustus/symaira-scope',
    button: t('scopeBtn'),
    icon: <Compass size={24} />,
    tone: 'indigo',
    demoType: 'scope',
    proHint: t('scopeProHint'),
    category: 'security',
  },
  {
    cmd: 'symeraseme',
    badge: t('erasemeBadge'),
    status: t('erasemeStatus'),
    title: t('erasemeTitle'),
    desc: t('erasemeDesc'),
    bestFor: t('erasemeBestFor'),
    automates: t('erasemeAutomates'),
    features: [t('erasemeFeature1'), t('erasemeFeature2'), t('erasemeFeature3'), t('erasemeFeature4')],
    href: 'https://github.com/danieljustus/symaira-eraseme',
    button: t('erasemeBtn'),
    icon: <Eye size={24} />,
    tone: 'ice',
    demoType: 'eraseme',
    proHint: t('erasemeProHint'),
    category: 'security',
  },
  {
    cmd: 'symterminal',
    badge: t('terminalBadge'),
    status: t('terminalStatus'),
    title: t('terminalTitle'),
    desc: t('terminalDesc'),
    bestFor: t('terminalBestFor'),
    automates: t('terminalAutomates'),
    features: [t('terminalFeature1'), t('terminalFeature2'), t('terminalFeature3'), t('terminalFeature4')],
    href: 'https://github.com/danieljustus/symaira-terminal',
    button: t('terminalBtn'),
    icon: <Terminal size={24} />,
    tone: 'mint',
    demoType: 'terminal-app',
    proHint: t('terminalProHint'),
    category: 'system',
  },
  {
    cmd: 'symvibe',
    badge: t('vibecoderBadge'),
    status: t('vibecoderStatus'),
    title: t('vibecoderTitle'),
    desc: t('vibecoderDesc'),
    bestFor: t('vibecoderBestFor'),
    automates: t('vibecoderAutomates'),
    features: [t('vibecoderFeature1'), t('vibecoderFeature2'), t('vibecoderFeature3'), t('vibecoderFeature4')],
    href: 'https://github.com/danieljustus/symaira-vibecoder',
    button: t('vibecoderBtn'),
    icon: <Workflow size={24} />,
    tone: 'violet',
    demoType: 'vibecoder',
    proHint: t('vibecoderProHint'),
    category: 'system',
  },
  {
    cmd: 'symoperate',
    badge: t('operateBadge'),
    status: t('operateStatus'),
    title: t('operateTitle'),
    desc: t('operateDesc'),
    bestFor: t('operateBestFor'),
    automates: t('operateAutomates'),
    features: [t('operateFeature1'), t('operateFeature2'), t('operateFeature3'), t('operateFeature4')],
    href: 'https://github.com/danieljustus/symaira-operate',
    button: t('operateBtn'),
    icon: <MousePointerClick size={24} />,
    tone: 'rose',
    demoType: 'operate',
    proHint: t('operateProHint'),
    category: 'system',
  },
  {
    cmd: 'symtune',
    badge: t('tuneBadge'),
    status: t('tuneStatus'),
    title: t('tuneTitle'),
    desc: t('tuneDesc'),
    bestFor: t('tuneBestFor'),
    automates: t('tuneAutomates'),
    features: [t('tuneFeature1'), t('tuneFeature2'), t('tuneFeature3'), t('tuneFeature4')],
    href: 'https://github.com/danieljustus/symaira-tune',
    button: t('tuneBtn'),
    icon: <Cpu size={24} />,
    tone: 'amber',
    demoType: 'tune',
    proHint: t('tuneProHint'),
    category: 'system',
  },
  {
    cmd: 'symfritz',
    badge: t('fritzBadge'),
    status: t('fritzStatus'),
    title: t('fritzTitle'),
    desc: t('fritzDesc'),
    bestFor: t('fritzBestFor'),
    automates: t('fritzAutomates'),
    features: [t('fritzFeature1'), t('fritzFeature2'), t('fritzFeature3'), t('fritzFeature4')],
    href: 'https://github.com/danieljustus/symaira-fritz',
    button: t('fritzBtn'),
    icon: <Router size={24} />,
    tone: 'sky',
    demoType: 'fritz',
    proHint: t('fritzProHint'),
    category: 'system',
  },
  {
    cmd: 'symguard',
    badge: t('guardBadge'),
    status: t('guardStatus'),
    title: t('guardTitle'),
    desc: t('guardDesc'),
    bestFor: t('guardBestFor'),
    automates: t('guardAutomates'),
    features: [t('guardFeature1'), t('guardFeature2'), t('guardFeature3'), t('guardFeature4')],
    href: 'https://github.com/danieljustus/symaira-guard',
    button: t('guardBtn'),
    icon: <ShieldAlert size={24} />,
    tone: 'indigo',
    demoType: 'guard',
    proHint: t('guardProHint'),
    category: 'security',
  },
  {
    cmd: 'symprint',
    badge: t('printBadge'),
    status: t('printStatus'),
    title: t('printTitle'),
    desc: t('printDesc'),
    bestFor: t('printBestFor'),
    automates: t('printAutomates'),
    features: [t('printFeature1'), t('printFeature2'), t('printFeature3'), t('printFeature4')],
    href: 'https://github.com/danieljustus/symaira-print',
    button: t('printBtn'),
    icon: <Printer size={24} />,
    tone: 'coral',
    demoType: 'print',
    proHint: t('printProHint'),
    category: 'context',
  },
  {
    cmd: 'symskills',
    badge: t('skillsBadge'),
    status: t('skillsStatus'),
    title: t('skillsTitle'),
    desc: t('skillsDesc'),
    bestFor: t('skillsBestFor'),
    automates: t('skillsAutomates'),
    features: [t('skillsFeature1'), t('skillsFeature2'), t('skillsFeature3'), t('skillsFeature4')],
    href: 'https://github.com/danieljustus/symaira-skills',
    button: t('skillsBtn'),
    icon: <Layers size={24} />,
    tone: 'mint',
    demoType: 'skills',
    proHint: t('skillsProHint'),
    category: 'system',
  },
  {
    cmd: 'symingest',
    badge: t('ingestBadge'),
    status: t('ingestStatus'),
    title: t('ingestTitle'),
    desc: t('ingestDesc'),
    bestFor: t('ingestBestFor'),
    automates: t('ingestAutomates'),
    features: [t('ingestFeature1'), t('ingestFeature2'), t('ingestFeature3'), t('ingestFeature4')],
    href: 'https://github.com/danieljustus/symaira-ingest',
    button: t('ingestBtn'),
    icon: <Upload size={24} />,
    tone: 'amber',
    demoType: 'ingest',
    proHint: t('ingestProHint'),
    category: 'context',
  },
  {
    cmd: 'symdesk',
    badge: t('desktopBadge'),
    status: t('desktopStatus'),
    title: t('desktopTitle'),
    desc: t('desktopDesc'),
    bestFor: t('desktopBestFor'),
    automates: t('desktopAutomates'),
    features: [t('desktopFeature1'), t('desktopFeature2'), t('desktopFeature3'), t('desktopFeature4')],
    href: 'https://github.com/danieljustus/symaira-desktop',
    button: t('desktopBtn'),
    icon: <Layout size={24} />,
    tone: 'violet',
    demoType: 'desktop',
    proHint: t('desktopProHint'),
    category: 'system',
  },
];
